### ISSUE TITLE
issue when import Quaternions, Symbol not found: __ZNKSt5ctypeIcE13_M_widen_initEv

### ISSUE THREAD

**Issue by eva-yhuang** [moble/GWFrames#54]
Hi, 
I also post this for Quaternions, but I am wondering if you guys have seen this before. When running `import GWFrames`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "GWFrames/__init__.py", line 9, in <module>
    import Quaternions
  File "/Users/Evalien/.local/lib/python2.7/site-packages/Quaternions/__init__.py", line 21, in <module>
    _Quaternions = swig_import_helper()
  File "/Users/Evalien/.local/lib/python2.7/site-packages/Quaternions/__init__.py", line 20, in swig_import_helper
    return importlib.import_module('_Quaternions')
  File "/Users/Evalien/miniconda3/envs/python2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: dlopen(/Users/Evalien/.local/lib/python2.7/site-packages/_Quaternions.so, 2): Symbol not found: __ZNKSt5ctypeIcE13_M_widen_initEv
  Referenced from: /Users/Evalien/.local/lib/python2.7/site-packages/_Quaternions.so
  Expected in: /usr/lib/libstdc++.6.0.9.dylib
```
I am running Python 2.7 on Mac High Sierra. I know you mentioned you guys no longer actively maintain this package, but I am trying to use code that uses this package. Thanks a ton in advance!

**Comment by moble** [comment]
Closing in favor of moble/Quaternions#11
